apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80  # Port inside the cluster
      targetPort: 80  # Container port
  type: LoadBalancer  # This will provision a cloud LoadBalancer for external access
