name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker image ls
        docker build -t weaverbeaver/argocd-nginx:latest .
        docker image push weaverbeaver/argocd-nginx:latest

